spring.application.name=dawBB

# Configuracion de la base de datos H2 en memoria
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.datasource.url=jdbc:h2:./daw
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=sa
spring.jpa.hibernate.ddl-auto=update

# Mostrar las consultas SQL en la consola
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Configuracion para generar el script SQL de creacion de la base de datos
#spring.jpa.properties.jakarta.persistence.schema-generation.scripts.action=create
#spring.jpa.properties.jakarta.persistence.schema-generation.scripts.create-target=nuevo-esquema.sql

jwt.secret=desarrollodeaplicacionesweb20252026desarrollodeaplicacionesweb20252026
